### ISSUE TITLE
[Bug] GaxiosError: Requested entity was not found.

### ISSUE THREAD

**Issue by guyzyl** [guyzyl/whatsapp-contact-sync#143]
```
GaxiosError: Internal error encountered.
    at Gaxios._request (/app/server/node_modules/gaxios/build/src/gaxios.js:130:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OAuth2Client.requestAsync (/app/server/node_modules/google-auth-library/build/src/auth/oauth2client.js:368:18)
```

**Comment by guyzyl** [comment]
Hasn't happened in a while.
